-- SEQUENCES

-- CRIAÇAO BASICA
CREATE SEQUENCE seq_Teste01
	AS NUMERIC
	START WITH 1
	INCREMENT BY 1

SELECT NEXT VALUE FOR seq_Teste01

--VALORES MAXIMOS E MINIMOS
CREATE SEQUENCE seq_Teste02
	AS NUMERIC
	START WITH 1
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 1000
	
--ALTERAR UMA SEQUENCE
ALTER SEQUENCE seq_Teste02
	RESTART WITH 1000
	MAXVALUE 10000

-- APAGAR SEQUENCE
DROP SEQUENCE seq_Teste02

-- Mostrar as sequences
select * from sys.sequences 